### ISSUE TITLE
Python "as" statements ruin 2.5 compatibility

### ISSUE THREAD

**Issue by darkvertex** [NetAngels/openssh-wrapper#7]
Hi! Unfortunately I'm in a platform currently stuck in Python 2.5 and cannot use this module because the "as" statements are a new feature in Python 2.6. In the interest of broader support, I would urge you to reconsider this syntax.

My pip install fails as follows:

```
Installing collected packages: openssh-wrapper
  Running setup.py install for openssh-wrapper
      File "/usr/local/lib/python2.5/site-packages/openssh_wrapper.py", line 176
        except IOError as exc:
                        ^
    SyntaxError: invalid syntax
```

**Comment by darkvertex** [comment]
Also the "io" module is new in 2.6

**Comment by darkvertex** [comment]
One more thing, your line:

``` python
if sys.version[0] == 2:
```

fails because (at least in Python 2.5, maybe older also) [0] will return a string, not an integer. Should be:

``` python
if sys.version[0] == '2':
```

I have got your module working with the above change, switching "io.open" for "open" and "as exc:" for ", exc:" -- but letting you know so you are aware should you be interested in supporting old versions better.

**Comment by sunweaver** [comment]
Python2.5 is ancient and "io" module is needed. Probably target 2.6+ compat only?

**Comment by darkvertex** [comment]
This issue is 4 years old and my environment is now on 2.7 so I'm going to go ahead and close this issue.

I agree that 2.5 is ancient and not worth the trouble.
